### ISSUE TITLE
build fail.

### ISSUE THREAD

**Issue by kouzhudong** [OpenVPN/tap-windows6#156]
E:\code\NetWork\OpenVPN\tap-windows6>buildtap.py --sdk=WDK -b
***** BUILD TAP config
Traceback (most recent call last):
  File "E:\code\NetWork\OpenVPN\tap-windows6\buildtap.py", line 511, in <module>
    btw.build()
  File "E:\code\NetWork\OpenVPN\tap-windows6\buildtap.py", line 280, in build
    self.build_tap()
  File "E:\code\NetWork\OpenVPN\tap-windows6\buildtap.py", line 255, in build_tap
    self.config_tap()
  File "E:\code\NetWork\OpenVPN\tap-windows6\buildtap.py", line 198, in config_tap
    self.preprocess(kv, os.path.join(self.src, "tap-windows6.vcxproj"))
  File "E:\code\NetWork\OpenVPN\tap-windows6\buildtap.py", line 190, in preprocess
    modtxt = re.sub(self.macro_amper, repfn, f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

E:\code\NetWork\OpenVPN\tap-windows6>

**Comment by rainroot** [comment]
src/tap-windows6.vcxproj.in file format change... ( UTF-8 )
